services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny10"
      DISK_SIZE: "16G"
      DISK2_SIZE: "2G"
      RAM_SIZE: "6G"
      LANGUAGE: "Ukrainian"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
